# Generated by Django 5.0.1 on 2024-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(default='')),
                ('year', models.PositiveIntegerField(default=2024)),
                ('imgThumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
